### PR TITLE
Java encoding and decoding improvements & fixes

### PR DESCRIPTION
**Pull request by springmeyer**
This PR includes various improvements and fixes to the java implementation.

It includes several fix issues in the non-vectorized path, bringing it back up to speed with the vectorized path:
 - #134 
 - #131 
 - #130 

And in includes two general encoding features that were missing:

 - #132 
 - #127

Additional changes, that don't have corresponding tickets:

 - Fixed the Delta encoding in the non-vectorized path to support RLE without multiple passes
 - Improves the `encode` and `decode` cli tools to actually decode vectorized geometries when `-decode` arg is passed
 - Make the spotless check run faster (avoids running builds and tests and just does the formatting check)
 - Fixes a small bug in the vectorized path where the signed boolean was incorrect
 - Makes the benchmark timer in the encode and decode tools quiet by default and now behind an option
 - Adds additional error detail when unsupported encodings are encountered at runtime
 - Comments some unused code
 - Renames some code to match naming better between the vectorized and non-vectorized path

### CODE REVIEW

**Comment by springmeyer** [comment]
This is now passing on CI and ready for review. Its a big one, but hopefully is still reviewable. The PR description has a summary to orient the reader.

**Comment by springmeyer** [comment]
Here is an overall status report of which paths works for which tiles. A ✔️ means that a tile can be encoded and decoded without exceptions. A ✖️ means some exception was thrown.

| fixture | default | advanced non-vector | advanced vector |
|---------|---------|---------------------|-----------------|
|./test/fixtures/omt/10_532_684.mvt|✘|✘|✔|
|./test/fixtures/omt/10_533_683.mvt|✘|✘|✔|
|./test/fixtures/omt/8_133_171.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1063_1368.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1062_1368.mvt|✔|✔|✔|
|./test/fixtures/omt/8_133_170.mvt|✔|✔|✔|
|./test/fixtures/omt/10_533_682.mvt|✘|✘|✔|
|./test/fixtures/omt/6_32_42.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8296_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/8_132_171.mvt|✔|✔|✔|
|./test/fixtures/omt/10_532_683.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4265_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4264_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/10_532_682.mvt|✘|✘|✔|
|./test/fixtures/omt/8_132_170.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8296_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/6_32_41.mvt|✔|✔|✔|
|./test/fixtures/omt/5_17_20.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8300_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/14_8300_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/10_533_684.mvt|✘|✘|✔|
|./test/fixtures/omt/5_17_21.mvt|✔|✔|✔|
|./test/fixtures/omt/2_2_2.mvt|✔|✔|✔|
|./test/fixtures/omt/10_530_683.mvt|✘|✘|✔|
|./test/fixtures/omt/10_530_682.mvt|✘|✘|✔|
|./test/fixtures/omt/12_2131_2733.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2130_2733.mvt|✔|✔|✔|
|./test/fixtures/omt/7_67_85.mvt|✔|✔|✔|
|./test/fixtures/omt/7_67_84.mvt|✔|✔|✔|
|./test/fixtures/omt/10_531_684.mvt|✘|✘|✔|
|./test/fixtures/omt/12_2131_2734.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2130_2734.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8297_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/4_3_9.mvt|✔|✔|✔|
|./test/fixtures/omt/10_530_684.mvt|✘|✘|✔|
|./test/fixtures/omt/14_8297_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/6_34_41.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4266_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4267_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/10_531_683.mvt|✘|✘|✔|
|./test/fixtures/omt/7_67_83.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1064_1368.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1065_1368.mvt|✔|✔|✔|
|./test/fixtures/omt/3_4_5.mvt|✔|✔|✔|
|./test/fixtures/omt/6_34_42.mvt|✔|✔|✔|
|./test/fixtures/omt/10_531_682.mvt|✘|✘|✔|
|./test/fixtures/omt/8_134_170.mvt|✔|✔|✔|
|./test/fixtures/omt/8_134_171.mvt|✔|✔|✔|
|./test/fixtures/omt/4_8_10.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4266_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4267_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1065_1366.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1064_1366.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1064_1367.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1065_1367.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2134_2733.mvt|✘|✘|✔|
|./test/fixtures/omt/9_266_341.mvt|✔|✔|✔|
|./test/fixtures/omt/5_16_21.mvt|✔|✔|✔|
|./test/fixtures/omt/5_16_20.mvt|✔|✔|✔|
|./test/fixtures/omt/6_33_41.mvt|✔|✔|✔|
|./test/fixtures/omt/9_266_340.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2134_2734.mvt|✘|✘|✔|
|./test/fixtures/omt/9_266_342.mvt|✔|✔|✔|
|./test/fixtures/omt/8_135_170.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8299_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/14_8299_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/6_33_42.mvt|✔|✔|✔|
|./test/fixtures/omt/8_135_171.mvt|✔|✔|✔|
|./test/fixtures/omt/7_66_84.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4265_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4264_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/9_264_341.mvt|✔|✔|✔|
|./test/fixtures/omt/9_264_340.mvt|✔|✔|✔|
|./test/fixtures/omt/7_66_85.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2132_2734.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2133_2734.mvt|✘|✔|✔|
|./test/fixtures/omt/9_264_342.mvt|✔|✔|✔|
|./test/fixtures/omt/7_68_83.mvt|✔|✔|✔|
|./test/fixtures/omt/9_265_342.mvt|✘|✘|✘|
|./test/fixtures/omt/7_66_83.mvt|✔|✔|✔|
|./test/fixtures/omt/7_68_84.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8298_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/9_265_341.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1062_1366.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1063_1366.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1063_1367.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1062_1367.mvt|✘|✘|✔|
|./test/fixtures/omt/9_265_340.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2132_2733.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2133_2733.mvt|✘|✔|✔|
|./test/fixtures/omt/14_8298_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/7_68_85.mvt|✔|✔|✔|


Note: this was generated with this script:

```bash
#!/usr/bin/env bash
trap "exit" INT

function run () {
    local msg=$1
    local cmd=$2
    RESULT_ERROR=$(${cmd} 2>&1 >/dev/null)
    RETURN_CODE=$?
    if [[ ${RETURN_CODE} == 0 ]]; then
        echo -n "✔"
    else
        echo -n "✘ $RESULT_ERROR"
    fi
}

echo "| fixture | default | advanced non-vector | advanced vector |"
echo "|---------|---------|---------------------|-----------------|"
tiles=$(find ./test/fixtures -type f \( -name "*.mvt" -o -name "*.pbf" \))
for fixture in ${tiles}; do
    # uncomment these lines to debug the input tiles
    # ~/projects/vtzero/build/examples/vtzero-show ${pbf_path}
    # vt2geojson -z 0 -x 0 -y 0 ${fixture}
    echo -n "|"
    echo -n "${fixture}"
    cd java
    echo -n "|"
    run "non-advanced non-vectorized" "java -jar build/libs/encode.jar -mvt ../${fixture} -decode"
    echo -n "|"
    run "advanced non-vectorized" "java -jar build/libs/encode.jar -mvt ../${fixture} -decode -advanced"
    echo -n "|"
    run "advanced vectorized" "java -jar build/libs/encode.jar -mvt ../${fixture} -decode -advanced -vectorized"
    echo "|"
    cd ../
done
```
```

**Comment by springmeyer** [comment]
Here is an overall status report of which tiles are able to be round-trip parsed and decoded with a given code path:

| fixture | default | advanced non-vector | advanced vector |
|---------|---------|---------------------|-----------------|
|./test/fixtures/bing/4-8-5.mvt|✔|✔|✘|
|./test/fixtures/bing/5-16-9.mvt|✔|✔|✘|
|./test/fixtures/bing/7-66-44.mvt|✔|✔|✘|
|./test/fixtures/bing/5-17-10.mvt|✔|✔|✘|
|./test/fixtures/bing/5-17-11.mvt|✔|✔|✘|
|./test/fixtures/bing/7-66-42.mvt|✔|✔|✘|
|./test/fixtures/bing/5-15-10.mvt|✔|✔|✘|
|./test/fixtures/bing/7-66-43.mvt|✔|✔|✘|
|./test/fixtures/bing/4-9-5.mvt|✔|✔|✘|
|./test/fixtures/bing/6-33-22.mvt|✔|✔|✘|
|./test/fixtures/bing/4-13-6.mvt|✔|✔|✘|
|./test/fixtures/bing/5-16-11.mvt|✔|✔|✘|
|./test/fixtures/bing/7-65-42.mvt|✔|✔|✘|
|./test/fixtures/bing/6-32-22.mvt|✔|✔|✘|
|./test/fixtures/bing/4-12-6.mvt|✔|✔|✘|
|./test/fixtures/bing/6-32-23.mvt|✔|✔|✘|
|./test/fixtures/bing/6-32-21.mvt|✔|✔|✘|
|./test/fixtures/amazon/5_16_11.pbf|✔|✔|✔|
|./test/fixtures/amazon/5_6_21.pbf|✔|✔|✔|
|./test/fixtures/amazon/9_259_176.pbf|✔|✔|✔|
|./test/fixtures/amazon/5_5_11.pbf|✔|✔|✔|
|./test/fixtures/amazon/6_33_21.pbf|✔|✔|✔|
|./test/fixtures/amazon/7_68_44.pbf|✔|✔|✔|
|./test/fixtures/amazon/8_136_89.pbf|✔|✔|✔|
|./test/fixtures/amazon/6_33_22.pbf|✔|✔|✔|
|./test/fixtures/amazon/10_518_352.pbf|✔|✔|✔|
|./test/fixtures/amazon/5_8_12.pbf|✔|✔|✔|
|./test/fixtures/amazon/11_1037_704.pbf|✔|✔|✔|
|./test/fixtures/amazon_here/5_16_10.pbf|✘|✘|✘|
|./test/fixtures/amazon_here/4_9_4.pbf|✘|✘|✘|
|./test/fixtures/amazon_here/8_132_85.pbf|✘|✘|✘|
|./test/fixtures/amazon_here/4_8_5.pbf|✘|✘|✘|
|./test/fixtures/amazon_here/6_33_22.pbf|✘|✘|✘|
|./test/fixtures/omt/10_532_684.mvt|✘|✘|✔|
|./test/fixtures/omt/10_533_683.mvt|✘|✘|✔|
|./test/fixtures/omt/8_133_171.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1063_1368.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1062_1368.mvt|✔|✔|✔|
|./test/fixtures/omt/8_133_170.mvt|✔|✔|✔|
|./test/fixtures/omt/10_533_682.mvt|✘|✘|✔|
|./test/fixtures/omt/6_32_42.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8296_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/8_132_171.mvt|✔|✔|✔|
|./test/fixtures/omt/10_532_683.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4265_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4264_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/10_532_682.mvt|✘|✘|✔|
|./test/fixtures/omt/8_132_170.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8296_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/6_32_41.mvt|✔|✔|✔|
|./test/fixtures/omt/5_17_20.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8300_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/14_8300_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/10_533_684.mvt|✘|✘|✔|
|./test/fixtures/omt/5_17_21.mvt|✔|✔|✔|
|./test/fixtures/omt/2_2_2.mvt|✔|✔|✔|
|./test/fixtures/omt/10_530_683.mvt|✘|✘|✔|
|./test/fixtures/omt/10_530_682.mvt|✘|✘|✔|
|./test/fixtures/omt/12_2131_2733.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2130_2733.mvt|✔|✔|✔|
|./test/fixtures/omt/7_67_85.mvt|✔|✔|✔|
|./test/fixtures/omt/7_67_84.mvt|✔|✔|✔|
|./test/fixtures/omt/10_531_684.mvt|✘|✘|✔|
|./test/fixtures/omt/12_2131_2734.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2130_2734.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8297_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/4_3_9.mvt|✔|✔|✔|
|./test/fixtures/omt/10_530_684.mvt|✘|✘|✔|
|./test/fixtures/omt/14_8297_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/6_34_41.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4266_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4267_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/10_531_683.mvt|✘|✘|✔|
|./test/fixtures/omt/7_67_83.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1064_1368.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1065_1368.mvt|✔|✔|✔|
|./test/fixtures/omt/3_4_5.mvt|✔|✔|✔|
|./test/fixtures/omt/6_34_42.mvt|✔|✔|✔|
|./test/fixtures/omt/10_531_682.mvt|✘|✘|✔|
|./test/fixtures/omt/8_134_170.mvt|✔|✔|✔|
|./test/fixtures/omt/8_134_171.mvt|✔|✔|✔|
|./test/fixtures/omt/4_8_10.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4266_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4267_5467.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1065_1366.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1064_1366.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1064_1367.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1065_1367.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2134_2733.mvt|✘|✘|✔|
|./test/fixtures/omt/9_266_341.mvt|✔|✔|✔|
|./test/fixtures/omt/5_16_21.mvt|✔|✔|✔|
|./test/fixtures/omt/5_16_20.mvt|✔|✔|✔|
|./test/fixtures/omt/6_33_41.mvt|✔|✔|✔|
|./test/fixtures/omt/9_266_340.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2134_2734.mvt|✘|✘|✔|
|./test/fixtures/omt/9_266_342.mvt|✔|✔|✔|
|./test/fixtures/omt/8_135_170.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8299_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/14_8299_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/6_33_42.mvt|✔|✔|✔|
|./test/fixtures/omt/8_135_171.mvt|✔|✔|✔|
|./test/fixtures/omt/7_66_84.mvt|✔|✔|✔|
|./test/fixtures/omt/13_4265_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/13_4264_5468.mvt|✘|✘|✔|
|./test/fixtures/omt/9_264_341.mvt|✔|✔|✔|
|./test/fixtures/omt/9_264_340.mvt|✔|✔|✔|
|./test/fixtures/omt/7_66_85.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2132_2734.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2133_2734.mvt|✘|✔|✔|
|./test/fixtures/omt/9_264_342.mvt|✔|✔|✔|
|./test/fixtures/omt/7_68_83.mvt|✔|✔|✔|
|./test/fixtures/omt/9_265_342.mvt|✘|✘|✘|
|./test/fixtures/omt/7_66_83.mvt|✔|✔|✔|
|./test/fixtures/omt/7_68_84.mvt|✔|✔|✔|
|./test/fixtures/omt/14_8298_10749.mvt|✘|✘|✔|
|./test/fixtures/omt/9_265_341.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1062_1366.mvt|✔|✔|✔|
|./test/fixtures/omt/11_1063_1366.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1063_1367.mvt|✘|✘|✔|
|./test/fixtures/omt/11_1062_1367.mvt|✘|✘|✔|
|./test/fixtures/omt/9_265_340.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2132_2733.mvt|✔|✔|✔|
|./test/fixtures/omt/12_2133_2733.mvt|✘|✔|✔|
|./test/fixtures/omt/14_8298_10748.mvt|✘|✘|✔|
|./test/fixtures/omt/7_68_85.mvt|✔|✔|✔|


Generated with this script:

```bash
#!/usr/bin/env bash
trap "exit" INT

function run () {
    local msg=$1
    local cmd=$2
    RESULT_ERROR=$(${cmd} 2>&1 >/dev/null)
    RETURN_CODE=$?
    if [[ ${RETURN_CODE} == 0 ]]; then
        echo -n "✔"
    else
        echo -n " ${RESULT_ERROR}"
    fi
}

echo "| fixture | default | advanced non-vector | advanced vector |"
echo "|---------|---------|---------------------|-----------------|"
tiles=$(find ./test/fixtures/bing -type f \( -name "*.mvt" -o -name "*.pbf" \))
for fixture in ${tiles}; do
    # uncomment these lines to debug the input tiles
    # ~/projects/vtzero/build/examples/vtzero-show ${pbf_path}
    # vt2geojson -z 0 -x 0 -y 0 ${fixture}
    echo -n "|"
    echo -n "${fixture}"
    cd java
    echo -n "|"
    run "non-advanced non-vectorized" "java -jar build/libs/encode.jar -mvt ../${fixture} -decode"
    echo -n "|"
    run "advanced non-vectorized" "java -jar build/libs/encode.jar -mvt ../${fixture} -decode -advanced"
    echo -n "|"
    run "advanced vectorized" "java -jar build/libs/encode.jar -mvt ../${fixture} -decode -advanced -vectorized"
    echo "|"
    cd ../
done
```

**Review by ebrelsford — APPROVED** [review]
As discussed, let's merge this as it is.

**Pull request merged**
