### PR TITLE
[WIP] Fix bing tiles decoding and add benchmarks

### PR DESCRIPTION
**Pull request by mactrem**
Initial Java benchmarks for the decoding performance of Bing Maps tiles into the MVT and MLT in-memory representations show about an order of magnitude improvement in the decoding performance compared to the 
java-vector-tile library and mapbox-vector-tile-java  library 

| Benchmark                             | Mode | Cnt | Score  | Error   | Units |
| ------------------------------------- | ---- | --- | ------ | ------- | ----- |
| BingMapsDecoderBenchmark.decodeMltZ4  | avgt | 5   | 0,561  | ± 0,149 | ms/op | 
| BingMapsDecoderBenchmark.decodeMltZ5  | avgt | 5   | 0,567  | ± 0,627 | ms/op | 
| BingMapsDecoderBenchmark.decodeMltZ6  | avgt | 5   | 0,239  | ± 0,195 | ms/op | 
| BingMapsDecoderBenchmark.decodeMltZ7  | avgt | 5   | 0,327  | ± 0,088 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvt2Z4 | avgt | 5   | 6,148  | ± 1,532 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvt2Z5 | avgt | 5   | 27,412 | ± 8,300 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvt2Z6 | avgt | 5   | 11,437 | ± 3,320 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvt2Z7 | avgt | 5   | 13,764 | ± 5,799 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvtZ4  | avgt | 5   | 9,470  | ± 5,041 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvtZ5  | avgt | 5   | 4,661  | ± 1,284 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvtZ6  | avgt | 5   | 2,052  | ± 0,246 | ms/op | 
| BingMapsDecoderBenchmark.decodeMvtZ7  | avgt | 5   | 3,477  | ± 0,479 | ms/op |

### CODE REVIEW

**Review by springmeyer — COMMENTED** [review]
This code needs formatted. Run `./gradlew spotlessApply` to do that. That will update `java/src/jmh/java/com/mlt/BenchmarkUtils.java`. I think the lint check must not be working in the PR (/cc @nyurik) otherwise this would be failing.

**Review by springmeyer — COMMENTED** [review]
I've run this locally and confirmed that this error is now fixed (which happened before with bing tiles for the `vectorized` path):

```
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:743)
	at java.base/java.nio.ByteBufferAsFloatBufferL.get(ByteBufferAsFloatBufferL.java:139)
	at com.mlt.decoder.vectorized.VectorizedFloatDecoder.decodeNullableFloatStream(VectorizedFloatDecoder.java:35)
	at com.mlt.decoder.vectorized.VectorizedPropertyDecoder.decodeToRandomAccessFormat(VectorizedPropertyDecoder.java:224)
	at com.mlt.decoder.MltDecoder.decodeMlTileVectorized(MltDecoder.java:164)
```


However a new one has showed up:

```
java.lang.IllegalArgumentException: ConstBooleanVector ist not supported yet.
	at com.mlt.decoder.vectorized.VectorizedPropertyDecoder.decodeToRandomAccessFormat(VectorizedPropertyDecoder.java:169)
	at com.mlt.decoder.MltDecoder.decodeMlTileVectorized(MltDecoder.java:164)
	at com.mlt.tools.Encode.main(Encode.java:254)|
```

To replicate:

```
cd java
./gradlew cli
java -jar build/libs/encode.jar -mvt ../test/fixtures/bing/5-16-9.mvt -decode -advanced -vectorized
```

**Review by springmeyer — APPROVED** [review]
Approving as this seems generally ready to merge once it is passing on CI (by pulling in latest `main` and ensuring the code is formatted).

**Comment by nyurik** [comment]
> This code needs formatted. Run `./gradlew spotlessApply` to do that. That will update `java/src/jmh/java/com/mlt/BenchmarkUtils.java`. I think the lint check must not be working in the PR (/cc @nyurik) otherwise this would be failing.

@springmeyer the lint check didn't run on this PR because this PR was not based on the latest main branch. Once I clicked the "update branch", it now includes the new "java lint" job that should fail

**Comment by nyurik** [comment]
as expected, it failed.  Run `just fmt` to reformat all code

**Comment by mactrem** [comment]
@springmeyer, those are the tiles I was talking about that the implementation for this special case is still missing. I will add the missing functionality in another PR

**Pull request merged**
