### PR TITLE
Introduce new repo structure

### PR DESCRIPTION
**Pull request by springmeyer**
This starts implementing #45.

### CODE REVIEW

**Comment by ebrelsford** [comment]
I'm sure you're still working on this but there are some dotfiles in `parser/js/` that probably should have been moved to `js/`

**Comment by springmeyer** [comment]
Yes very much a work in progress. But thanks I'll make sure I get the .dot files.

**Comment by nyurik** [comment]
just to double check on this PR -- shouldn't most of the changes be done before moving the files? This way git will retain the history - i.e. it will be able to track that the file was moved rather than deleted and created somewher else?

As this stands now, seems like lots of deletions and recreations, which is bad because it looses history.

**Comment by nyurik** [comment]
P.S. I do not mean any adjustments to the paths in the CI jobs, etc, to keep it in a testable state.

**Comment by springmeyer** [comment]
@nyurik agree that we should aim for moves rather than deletes + recreations. However some deletions are intentional as I'm taking the liberty to delete code that is old or not fitting in the new layout, like `./evaluation` and `js/src/evaluation`. So those intentional deletions might be what you are seeing. If you see recreations can you give an example and I'll take a closer look?

**Comment by springmeyer** [comment]
> P.S. I do not mean any adjustments to the paths in the CI jobs, etc, to keep it in a testable state.

@nyurik can you share more about what you mean?

**Comment by springmeyer** [comment]
I think this is ready for first review. What I recommend doing is:

 - Ignore looking at the diff at first
 - Rather check the branch out locally and have a look around locally
 - Make sure you can find all the code you'd expect to exist, in the places you'd expect
 - Go into the java or js folders and build + run the tests and make sure things run and work right
 - Comment back here about any problems or breakages and I'll make adjustments
 
Once we confirm that the general layout is okay and the builds + tests are still working for everyone that wants to test, then as a separate followup step let's revisit additional issues before merging:

 - Is it okay to delete the file I deleted (like `evaluation` folders)? If not, where should they be put in the new layout?
 - Are there any files that were moved which git is actually reporting as deletions and recreations?
 - Any changes I made during this re-org that you'd like to see landed as a separate PR (if only to review them easier?)

To solve these final issues I imagine I'll probably re-create a fresh new PR that re-runs the moves more carefully to make sure history is preserved as we'd expect.

**Comment by mactrem** [comment]
I have checked out the branch and tested locally on my machine. The build and tests of the Java project are working. Also the draft of the spec with the referenced documents (images, proto files, ...) is displayed correctly. From my side we can merge it

**Comment by springmeyer** [comment]
Great you both think this is ready to merge @mactrem @ebrelsford - Any concerns around deleted files now if you scan the diff?

@nyurik can you review as well?

**Comment by ebrelsford** [comment]
I don't see any issues with deletions, mostly noticing the redundant js module files getting consolidated, looks fine to me.

**Review by nyurik — APPROVED** [review]
awesome work, lets merge!

**Pull request merged**
