### PR TITLE
Google Java format

### PR DESCRIPTION
**Pull request by springmeyer**
We have prettier/ESLint for JS. This introduces consistent formatting tools for Java.

I don't personally have opinions about what formatter to use. Google's just seemed like a reasonable first place to start.

This uses https://github.com/diffplug/spotless/tree/main/plugin-gradle as a simple and efficient way to apply & enforce the Java format.

### CODE REVIEW

**Comment by nyurik** [comment]
i'm all for the stable code formatting (thx!). My only concern is if we have any significant code change PRs, merging them would be a bit more difficult due to merge conflicts. Are there any PRs that should be merged first?

**Review by nyurik — APPROVED** [review]
apppp

**Comment by springmeyer** [comment]
> My only concern is if we have any significant code change PRs, merging them would be a bit more difficult due to merge conflicts. Are there any PRs that should be merged first?

Yes, I plan to hold on this until it's 100% certain everything in-flight is merged (will confirm with folks in slack). But, wanted to get this going for initial review. Will mark draft for now to indicate I don't plan to merge yet.

**Comment by springmeyer** [comment]
Noting that this PR intended to check 2 things:

- 1. Confirming that the CI jobs for java failed, as intended, when adding a format check to the Gradle build + running `./gradlew build` on CI ✅ 
- 2. Confirming that the CI jobs passed for java when applying the java formatting locally and then pushing the results ✅ 

Now that 2 is confirmed, I'll revert 2 in order to make this PR mergable without merge conflicts against other in-flight PRs. Then we can circle back separately to decide when to apply the formatting overall. Sound good?

**Comment by nyurik** [comment]
Sounds good. Do you want to make #116 change (file paths in `org/maplibre/mlt` style) here too?

**Comment by springmeyer** [comment]
> Do you want to make https://github.com/maplibre/maplibre-tile-spec/issues/116 change (file paths in org/maplibre/mlt style) here too?

That feels like it could break in-flight PRs. So I'm thinking to merge this without additional/any breaking changes. Then followup with a formatting PR that changes the code in src/ and then yes, adding in #116 would be great.

**Comment by nyurik** [comment]
hope we can merge this soonish (and run the global reformat)

**Pull request merged**
