### PR TITLE
Add licensing information

### PR DESCRIPTION
**Pull request by nyurik**
This PR sets the following licensing rules for this repository.

* All project documentation and specification content is licensed under [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/) - Public Domain Dedication.
* All code is dual licensed under [Apache License v2.0](http://www.apache.org/licenses/LICENSE-2.0) and [MIT license](http://opensource.org/licenses/MIT), at your option.
* Tile test data in the `/test` directory has different licenses depending on the source of that data.

#### For new contributors

Readme also contains this text for new contributors.  I adapted the standard text used by other repos to include CC0 vs MIT/Apache distinction.

> Unless you explicitly state otherwise, any code contribution intentionally
> submitted for inclusion in the work by you, as defined in the
> Apache-2.0 license, shall be dual licensed as above, without any
> additional terms or conditions. Similarly, any documentation or specification
> contributions shall be licensed under CC0 1.0 Universal.

### Contributors

These contributors show up in [GitHub](https://github.com/maplibre/maplibre-tile-spec/graphs/contributors) for this repo.  Everyone, please leave a comment below, acknowledging this change.

* Markus Tremmel @mactrem
* Dane Springmeyer @springmeyer
* Eric Brelsford @ebrelsford
* Yuri Astrakhan @nyurik
* Yi Zhang @zhangyiatmicrosoft
* Ante Viducic @etnav
* Felix Fischer @FF-98
* ??? @Gh0stD3x

### CODE REVIEW

**Comment by ebrelsford** [comment]
Acknowledged.

**Comment by mactrem** [comment]
Acknowledged

**Comment by springmeyer** [comment]
Acknowledged

**Review by springmeyer — APPROVED** [review]

**Comment by etnav** [comment]
Acknowledged.

**Comment by zhangyiatmicrosoft** [comment]
Acknowledged

**Comment by FF-98** [comment]
Acknowledged.
Sorry for the empty profile, my name is Felix Fischer.

**Comment by tom-nom-nom** [comment]
Acknowledged, my name is Tom Böhm, sry...

**Comment by Gh0stD3x** [comment]
Acknowledged. I thought i had already made a comment (Tom Böhm)

**Pull request merged**
